function raeng_regressionuk_resampled

%% Rjb

% directory = 'C:\GitHub\DouglasEtAl_UK_HEM_GMM\Resampled data\Rjb\';

periods=[
    {'0010'},...
    {'0025'},...
    {'0050'},{'0075'},{'0100'},{'0150'},{'0200'},...
    {'0300'},{'0400'},{'0500'},{'0750'},{'1000'},{'1500'},{'2000'},...
    {'3000'},{'4000'},{'5000'},{'7500'},{'9999'}
    ];

% for t=1:length(periods)
%     for i=1:5 % Number of branches
%         if i < 4
%             % Rjb original
%             raeng_regressionhybriduk_resampled( ...
%                 periods(t), ...
%                 [directory,'original3bothrjb',char(periods(t)),'.txt'], ...
%                 ['coeffukrjbboth_3branches_original_',char(periods(t))], ...
%                 11, ...
%                 i);
% 
%             % Rjb reweighted
%             raeng_regressionhybriduk_resampled( ...
%                 periods(t), ...
%                 [directory,'reweighted3bothrjb',char(periods(t)),'.txt'], ...
%                 ['coeffukrjbboth_3branches_reweighted_',char(periods(t))], ...
%                 11, ...
%                 i);
%         end
%         % Rjb original
%         raeng_regressionhybriduk_resampled( ...
%             periods(t), ...
%             [directory,'original5bothrjb',char(periods(t)),'.txt'], ...
%             ['coeffukrjbboth_5branches_original_',char(periods(t))], ...
%             11, ...
%             i);
% 
%         % Rjb reweighted
%         raeng_regressionhybriduk_resampled( ...
%             periods(t), ...
%             [directory,'reweighted5bothrjb',char(periods(t)),'.txt'], ...
%             ['coeffukrjbboth_5branches_reweighted_',char(periods(t))], ...
%             11, ...
%             i);
%     end
% end

%% Rrup
directory = 'C:\GitHub\DouglasEtAl_UK_HEM_GMM\Resampled data\Rrup\';

for t=1:length(periods)
    for i=1:5 % Number of branches
        if i < 4
            % Rrup original        
            raeng_regressionhybriduk_resampled( ...
                periods(t), ...
                [directory,'original3bothrrup',char(periods(t)),'.txt'], ...
                ['coeffukrrupboth_3branches_original_',char(periods(t))], ...
                11, ...
                i);
    
            % Rrup reweighted
            raeng_regressionhybriduk_resampled( ...
                periods(t), ...
                [directory,'reweighted3bothrrup',char(periods(t)),'.txt'], ...
                ['coeffukrrupboth_3branches_reweighted_',char(periods(t))], ...
                11, ...
                i);
        end
        % Rrup original        
        raeng_regressionhybriduk_resampled( ...
            periods(t), ...
            [directory,'original5bothrrup',char(periods(t)),'.txt'], ...
            ['coeffukrrupboth_5branches_original_',char(periods(t))], ...
            11, ...
            i);

        % Rrup reweighted
        raeng_regressionhybriduk_resampled( ...
            periods(t), ...
            [directory,'reweighted5bothrrup',char(periods(t)),'.txt'], ...
            ['coeffukrrupboth_5branches_reweighted_',char(periods(t))], ...
            11, ...
            i);
    end
end
