function raeng_regressionhybriduk_resampled(period,infile,outfile,form,branch)
% --------------------------------------------------------------------------------
% regression(infile,outfile,form,method,soilmethod,mech,mechanism,figures)
% INFILE=Name of file containing filenames of files with spectral values
% OUTFILE=Name of output file containing coefficients to produce
% FORM=1, ..., 9:
%                           1 implies log y=b1+b2 M+b3 log(sqrt(d^2+b5^2))+b4 (sqrt(d^2+b5^2))
%                           2 implies log y=b1+b2 M+b3 log(sqrt(d^2+b4^2))
%                           3 implies log y=b1+b2 M+b3 M^2+b4 log(sqrt(d^2+b6^2))+b5 (sqrt(d^2+b6^2))
%                           4 implies log y=b1+b2 M+b3 M^2+b4 log(sqrt(d^2+b5^2))
%                           5 implies log y=b1+b2 log(sqrt(d^2+b4^2))+b3 (sqrt(d^2+b4^2))
%                           6 implies log y=b1+b2 log(sqrt(d^2+b3^2))
%                           7 implies log y=b1+b2 M-log(sqrt(d^2+b4^2))+b3(sqrt(d^2+b4^2))
%                           8 implies log y=b1+b2 M+b3 log(d+b4)
%                           9 implies log y=b1+b2 M+b3 M^2+b4*R+b5*log10(R+b6*10^(b7*M)
%                          10 implies log y=b1+b2 M+b3 d
%                          11 implies ln y=b1+b2 M+b3 (8.5-M)^2+b4 ln (sqrt(d^2+(b7 exp (b8 M))^2))+
%                                     (c5+c6 M)d +f3(d)
%                                     where f3(d)=0 for d<=r1
%                                           f3(d)=c9(ln d-ln r1) for r1<d<=r2
%                                           f3(d)=c9(ln d-ln r1)+c10 (ln d-ln r2) for d>r2
%
%
% Routine to calculate the spectral attenuation coefficients for all the dampings
% and periods stated in the input files.
%
% Required input file is INFILE which consists of a list of files
% generated by SPECATT.FOR. It sends these filenames to routine NLREGL.M
% which calculates the corresponding coefficients and returns them to this
% routine.
%
% N.B. New coefficients are appended to the end of file so need to
% delete old OUTFILEs unless want the new coefficients appended to
% end
%
% Can use ATTEN_PLT.M or PGA_PLT.M to plot results
%
% Author: J. Douglas
%
% History:
% -  2. 7.1999: Created
% -  2. 7.1999: Documented
% -  9. 8.1999: Added "both" variable
% - 25.10.1999: Changed to output matrix C and the number of datapoints
%				and coefficients found
% - 26.10.1999: Added lines to output header and changed to output a few new
%			    statistics.
% -  1.11.1999: Added depth option.
% -  2.11.1999: Corrected a problem with outputting when both horizontal and
%               vertical periods.
% -  3.11.1999: Documented depth option.
% -  1. 3.2001: Did some tidying up. Deleted redundant lines.
% -  1. 3.2001: Updated documentation.
% -  6. 1.2003: Improved structure and extendability of program.
% - 10. 1.2003: Started including soil coefficient calculation
% - 17. 1.2003: Improved outputting of results so that column labels match
%               with contents of column
% - 20. 1.2003: Added lines to output standard errors of all coefficients
% - 21. 1.2003: Implemented calculation of soil coefficients using method
%               (2)
% - 22. 1.2003: Implemented calculation of soil coefficients using method
%               (1) for all regression methods but 5.
% -  4.11.2003: Changed regression.m to create regressionhybrid.m for use
%               with files from CHEEP
% -  5.11.2003: Added Campbell (2003)'s functional form
%
% Last revision:  5.11.2003
% ---------------------------------------------------------------------------

tic

% Loop to calculate coefficients
[b,sd,seb,sig,dper,N,nc]=nlregl(str2num(char(period)),infile,form,branch);
neq=1;
nst=1;
nsd=length(sd);
ssd=['     sd1'];
ssdn=[' %7.4f '];
for l=1:nsd-1;
    ssd=[ssd,'      sd',num2str(l+1)];
    ssdn=[ssdn,' %7.4f '];
end
sb='';
sse='';
ss=' ';
sbn='';
ssen='';
ssn='';
for l=1:nc;
    sb=[sb,'        b',num2str(l),' '];
    sbn=[sbn,' %12.8f '];
    sse=[sse,'       se',num2str(l)];
    ss=[ss,' ',num2str(l),' '];
    ssen=[ssen,' %8.5f '];
    ssn=[ssn,' %1i '];
end

% Outputting to file
% Checking if new file if so outputs header
filename=[outfile,num2str(branch,'%1i'),'.txt'];
fid1=fopen(filename,'rt');
if fid1==-1
    newfile=1;
else
    newfile=0;
    fclose(fid1);
end
fid1 = fopen(filename,'at');
if newfile==1
    fprintf(fid1,['%1i %1i %2i %2i \n'],[form,1,-1,-1]);
    fprintf(fid1,['%s \n'],['Damp  Period',sb,ssd,sse,ss,'   N  Neq  Nst  c']);
end
fprintf(fid1,['%4.1f %7.4f',sbn,ssdn,ssen,ssn,'%4i %4i %4i %2i \n'],dper(1),dper(2),b,sd,seb,sig,N,neq,nst,nc);
fclose(fid1);

toc

function [b,sd,seb,sig,temp,n,nc]=nlregl(period,stem,form,branch)
% ----------------------------------------------------------------------------
% [b,sd,seb,sig,temp,n,neq,nst,nc]=nlregl(infile,form,method,soil,mech,mechanism,both,figures)
% INFILE= Name of input file holding spectral accelerations
% FORM=1, ..., 9:
%                           1 implies log y=b1+b2 M+b3 log(d^2+b5^2)+b4 (d^2+b5^2)
%                           2 implies log y=b1+b2 M+b3 log(d^2+b5^2)
%                           3 implies log y=b1+b2 M+b6 M^2+b3 log(d^2+b5^2)+b4 (d^2+b5^2)
%                           4 implies log y=b1+b2 M+b6 M^2+b3 log(d^2+b5^2)
%                           5 implies log y=b1+b3 log(d^2+b5^2)+b4 (d^2+b5^2)
%                           6 implies log y=b1+b3 log(d^2+b5^2)
%                           7 implies log y=b1+b2 M-log(sqrt(d^2+b4^2))+b4(sqrt(d^2+b4^2))
%                           8 implies log y=b1+b2 M+b3 log(d+b4)
%                           9 implies log y=b1+b2*M+b3*M^2+b4*R+b5*log10(R+b6*10^(b7*M)
%                          10 implies log y=b1+b2 M+b3 d
%                          11 implies ln y=b1+b2 M+b3 (8.5-M)^2+b4 ln (sqrt(d^2+(b7 exp (b8 M))^2))+
%                                     (c5+c6 M)d +f3(d)
%                                     where f3(d)=0 for d<=r1
%                                           f3(d)=c9(ln d-ln r1) for r1<d<=r2
%                                           f3(d)=c9(ln d-ln r1)+c10 (ln d-ln r2) for d>r2
%
%
% BOTH=0 or 1:
%                           0 implies only one damping and period specified
%                           1 implies both horizontal and vertical
%
% Routine to find the attenuation coefficients of the normal attenuation
% relation: log y=a1+a2M+a3logr+a4r where r=sqrt(d^2+a5^2)
% It does this through a nonlinear algorithm using Marquardt's algorithm has
% implimented by Osborne (1972).
%
% Input file required is: hspa*****.dat or vspa*****.dat which are table with
% 9 columns:
% WID, EID, SID, M, d, z, mech, soil, y
% N.B. First line contains damping and period.
% Files produced from SPECATT.FOR
%
% Generated output is a vector b with the five coefficients, the
% estimate of the standard deviation,sd, (from the residuals),a vector temp
% with two elements the damping and period, a vector seb with the standard
% error in the coefficients, R the coefficient of determination, a vector
% sig with 1 if the coefficient is significantly different than zero (using
% the t-test), Varb co-variance & variance matrix, n number of data points,
% nc number of coefficients found, totalun the total uncorrected sum of
% squares, meancor the correction due to mean, regression the sum of squares
% due to regression, F the F-value and sigF whether the equation is significant.
%
% N.B. Standard deviation, standard error in coefficients, significance and
% R have not yet been applied to alternative two-step as unsure as what
% correct definition is.
%
% Also generates files called ****.rsd with the input information from the
% input file and the residual between the predicted and actual accelerations.
%
% References:
% "Nonlinear Regression", Gallant, A.R. The American Statistician,
% Number 2, Volume 29, May 1975, pp. 73-81.
%
% "Some Aspects of Non-linear Least Squares Calculations", Osborne, M.R. in
% Numerical Methods for Non-linear Optimization, edited by Lootsma, F.A.,1972
% pp. 171-189.
%
% "Peak horizontal acceleration and velocity from strong-motion records
% including records from the 1979 Imperial Valley, California, earthquake"
% Joyner, W.B. and Boore, D.M. B.S.S.A., Vol. 71, No. 6, pp. 2011-2038,
% December 1981.
%
% "Measurement, characterization, and prediction of strong ground motion",
% Joyner, W.B. and Boore, D.M., Proceedings of Earthquake Engineering & Soil Dynamics II
% GT Div/ASCE, Park City, Utah, June 27-30,1988
%
% "Applied Regression Analysis", Draper, N.R. & Smith, H., 2nd Edition, John
% Wiley & Sons, 1981.
%
% "Applied Linear Regression", Weisburg, S., John Wiley & Sons, 1985.
%
% Author: J. Douglas
%
% History:
% - 21. 6.1999: Created NLREG.M.
% - 21. 6.1999: Checked using Ambraseys, Simpson and Bommer P.G.A. dataset.
%               Match is exact to significant figures of output.
% - 23. 6.1999: Corrected small error in G matrix
% - 23. 6.1999: Added two-step algorithm
% - 23. 6.1999: Added anelastic algorithm
% - 24. 6.1999: Corrected Cholesky decomposition algorithm
% - 25. 6.1999: Checked gradient and Hessian matrices. Checked rest of routine.
% - 29. 6.1999: Made small change to improve efficiency of algorithm
% -  1. 7.1999: Changed to work with new file format
% -  2. 7.1999: Made it able to be call from other routines
% -  2. 7.1999: Deleted plotting commands
% -  7. 7.1999: Added significance tests.
% -  9. 8.1999: Added "both" variable
% - 29. 9.1999: Added residual output file
% - 18.10.1999: Changed algorithm to Marquardt's method to create NLREGL.M
% - 19.10.1999: Implemented two-step method
% - 22.10.1999: Corrected a couple of mistakes and added alternative two-step
%					 method.
% - 25.10.1999: Changed to output the variance-covariance matrix, the number
%					 of datapoints and the number of coefficients
% - 26.10.1999: Changed to output a few new statistics.
% - 28.10.1999: Added lines to calculate and output Cook's distance
% - <1.11.1999: Added lines to enable user to specify minimum PGV of records
%					 to use
% -  1.11.1999: Added depth option.
% -  3.11.1999: Documented depth option and strain option.
% - 31. 1.2000: Corrected a few mistakes with the two-step method
% -  7. 2.2000: Added option to simply calculate the mean of the data
% -<18. 4.2000: Changed to read in waveform ID
% - 18. 4.2000: Changed to read in soil type and output to residual files
%               waveform ID and soil type
% - 14. 6.2000: Added weighted two-step algorithm and simplified other two-step algorithm
% - 15. 6.2000: Corrected weighted two-step algorithm
% -  1. 3.2001: Did some tidying up. Deleted redundant lines.
% -  6. 1.2003: Improved structure and extendability of program.
% -  7. 1.2003: Continued improving structure
% -  8. 1.2003: Continued improving structure and corrected 2-stage J & B (1988)
% -  9. 1.2003: Continued improving structure and added extra functional forms
% -  9. 1.2003: Changed to use feval rather than eval because about 4 times
%               faster
% - 10. 1.2003: Included Chen & Tsai's (2002) method.
% - 13. 1.2003: Added Chen & Tsai's (2002) functional form and checked
%               program with their data against their solution.
% - 17. 1.2003: Corrected an error with the outputting of the standard
%               errors of the two-stage method.
% - 20. 1.2003: Added lines to output standard errors of all coefficients
% - 21. 1.2003: Implemented calculation of soil coefficients using method
%               (2)
% - 22. 1.2003: Implemented calculation of soil coefficients using method
%               (1) for all regression methods but 5.
% -  4.11.2003: Changed nlregl.m for use with files from CHEEP
%
% Last Revision:  4.11.2003
% ------------------------------------------------------------------------------

format long

data=readtable(stem);
M=data.Var1';
d=data.Var2';
A=table2array(data);
y=log(A(:,branch+2)');


n=length(y)

% Required accuracy in answer
acc=1e-5;
% Significance to test for
sigl=0.05;

% choosing functional form
switch form
    % linear magnitude, geometric and anelastic decay
    case {1}
        c0=[1;0.3;-1;0;5];
        nc=length(c0);
        % Applying Marquardt's method
        func1=@attfunmga;
        [c,sd,Varb,fh,nc]=linnlreg(y,[M;d]',n,c0,nc,acc,func1);
        % linear magnitude and geometric decay
    case {2}
        % Starting values
        c0=[1;0.3;-1;5];
        nc=length(c0);
        % Applying Marquardt's method
        func1=@attfunmg;
        [c,sd,Varb,fh,nc]=linnlreg(y,[M;d]',n,c0,nc,acc,func1);
        % quadratic magnitude, geometric and anelastic decay
    case {3}
        c0=[1;0.3;-0.1;-1;0;5];
        nc=length(c0);
        % Applying Marquardt's method
        func1=@attfunmqga;
        [c,sd,Varb,fh,nc]=linnlreg(y,[M;d]',n,c0,nc,acc,func1);
        % quadratic magnitude and geometric decay
    case {4}
        c0=[1;0.3;-0.1;-1;5];
        nc=length(c0);
        % Applying Marquardt's method
        func1=@attfunmqg;
        [c,sd,Varb,fh,nc]=linnlreg(y,[M;d]',n,c0,nc,acc,func1);
        % no magnitude, geometric and anelastic decay
    case {5}
        c0=[1;-1;0;5];
        nc=length(c0);
        % Applying Marquardt's method
        func1=@attfunnmga;
        [c,sd,Varb,fh,nc]=linnlreg(y,d',n,c0,nc,acc,func1);
        % no magnitude and geometric decay
    case {6}
        c0=[1;-1;5];
        nc=length(c0);
        % Applying Marquardt's method
        func1=@attfunnmg;
        [c,sd,Varb,fh,nc]=linnlreg(y,d',n,c0,nc,acc,func1);
        % linear magnitude and geometric decay set to -1
    case {7}
        c0=[1;0.3;0;5];
        nc=length(c0);
        % Applying Marquardt's method
        func1=@attfunmm1a;
        [c,sd,Varb,fh,nc]=linnlreg(y,[M;d]',n,c0,nc,acc,func1);
        % linear magnitude and geometrical decay of form log10(d+h)
    case {8}
        c0=[1;0.3;-1;5];
        nc=length(c0);
        % Applying Marquardt's method
        func1=@attfunmgd;
        [c,sd,Varb,fh,nc]=linnlreg(y,[M;d]',n,c0,nc,acc,func1);
        % Chen & Tsai (2002)'s functional form
    case {9}
        c0=[-4;2;-0.1;0.0001;-2;0.1;0.2];
        nc=length(c0);
        % Applying Marquardt's method
        func1=@attfunct;
        [c,sd,Varb,fh,nc]=linnlreg(y,[M;d]',n,c0,nc,acc,func1);
    case {10}
        c0=[1;0.2;-0.001];
        nc=length(c0);
        % Applying Marquardt's method
        func1=@attfunmand;
        [c,sd,Varb,fh,nc]=linnlreg(y,[M;d]',n,c0,nc,acc,func1);
    case {11}
        c0=[0;0.5;-0.1;-1;0;0;0.5;0.5;1;-1];
        nc=length(c0);
        func1=@attfuncampbell;
        [c,sd,Varb,fh,nc]=linnlreg(y,[M;d]',n,c0,nc,acc,func1);
    case {12}
        c0=[0;0.5;-0.1;-1;0;0;0.5;0.5;0.5];
        nc=length(c0);
        func1=@attfunspain;
        [c,sd,Varb,fh,nc]=linnlreg(y,[M;d]',n,c0,nc,acc,func1);
end
% Copying coefficients to output vector
b=c(1:nc);
% Calculating standard errors in coefficients
seb=sqrt(diag(Varb));
seb=seb';
% Applying the t-test.
t=abs(b)./seb';
% Checking significance of coefficients
%ct=abs(ttestvalues(sigl,n-nc));
%ct=abs(tinv(sigl/2,n-nc));
%i1=find(t>ct);
sig=zeros(1,nc);
%sig(i1)=1;

temp=[5,period];

function [theta,sd,Varb,fh,nc]=linnlreg(Y,xi,n,theta,nc,acc,func1)
% ---------------------------------------------------------------------
% [theta,sd,Varb,fh]=linnlreg(Y,xi,n,theta,nc,acc,func1)
% Input:
% Y=n x 1 vector of measured accelerations
% xi=n x nc vector of (magnitudes and) distances
% n=number of data points
% theta=starting values of coefficients
% nc=number of coefficients
% acc=accuracy to achieve in coefficients
% func1=function name for functional form to use
%
% Output:
% theta=least squares coefficients
% sd=standard deviation
% Varb=approximate variance-covariance matrix
% fh=estimated accelerations
%
% Function to apply Marquardt's method (as implemented by Osborne (1972))
% for nonlinear regression. Uses a two step orthogonal factorization to
% improve efficiency.
%
% References:
% "Nonlinear Regression", Gallant, A.R. The American Statistician,
% Number 2, Volume 29, May 1975, pp. 73-81.
%
% "Some Aspects of Non-linear Least Squares Calculations", Osborne, M.R. in
% Numerical Methods for Non-linear Optimization, edited by Lootsma, F.A.,1972
% pp. 171-190.
%
% Author: J. Douglas
%
% History:
% - 18.10.1999: Created
% - 19.10.1999: Implemented two-step method
% - 20.10.1999: Improved efficiency slightly
% - 22.10.1999: Corrected a couple of mistakes and added alternative two-step
% -  1.11.1999: Added depth option.
% -  3.11.1999: Documented depth option.
% -  6. 1.2003: Improved structure and extendiability by using eval
% -  9. 1.2003: Changed to use feval rather than eval because about 4 times
%               faster
% - 20. 1.2003: Added lines to calculate standard errors of all coefficients
% - 22. 1.2003: Implemented calculation of soil coefficients using method
%               (1).
%
% Last revision: 22. 1.2003
% ----------------------------------------------------------------------------

f=zeros(1,n);
Z=zeros(n,nc);

% Increase factor for nu if another step has to be calculated
EXP=1.5;
% Decrease factor for nu if except current step
DECR=0.5;
% Reset count (if no convergence after 1000 steps then aborts calculation)
count=1;
% Reset sum of squares
ss=0;
% Loop to calculate initial derivative matrix and nu value
for i=1:n
    [f0,Z(i,1:nc)]=feval(func1,xi(i,:),theta(1:nc));
    ss=ss+sum(Z(i,1:nc).^2);
end

nu=sqrt(ss/(n*nc));
% Main loop repeats until convergence (or 1000 loops) is reached
b=ones(1,nc);
while(and(max(norm(b,inf))>acc,count<1000))
    % If not first step then calculates new derivate matrix
    if count>1
        for i=1:n
            [f0,Z(i,1:nc)]=feval(func1,xi(i,:),theta(1:nc));
        end
    end
    % First step of orthogonalization of derivative matrix
    [Q1,R1]=qr(Z,0);
    % Loop repeats until exceptable step is found
    ic=0;
    nf=1;
    nfh=nf+1;
    while(nfh>nf)
        % Second step of orthogonalization
        temp=[R1;zeros(1,nc);nu*eye(nc)];
        [Q2,R]=qr(temp,0);
        % Calculate new derivative matrix and function vector
        for i=1:n
            [f(i),Z(i,1:nc)]=feval(func1,xi(i,:),theta(1:nc));
        end
        nf=norm(Y-f,2);
        % Calculating step vector
        b=R'*R\(Z'*(Y-f)');
        % Calculating function vector with new coefficients
        for i=1:n
            [fh(i),z0]=feval(func1,xi(i,:),theta(1:nc)+b(1:nc));
        end
        nfh=norm(Y-fh,2);
        ic=ic+1;
        % Checking see whether new step is an improvement, if is not then increases
        % nu and repeats
        if(nfh>nf)
            nu=nu*EXP;
        end
    end
    % Updating coefficients vector
    theta=theta+b;
    % If first calculated step was exceptable then decreases nu
    if ic==1
        nu=nu*DECR;
    end
    count=count+1;
end

% Calculating standard deviation
sd=sqrt(nfh^2/(n-nc));
% Calculating co-variance matrix of coefficients
Varb=inv(Z'*Z)*sd^2;
