function raeng_regressionuk_resampled

%% GAB files

% directory = ['C:\GitHub\DouglasEtAl_UK_HEM_GMM\JD resampling\' ...
%     'GAB - Rrup resampled data\'];

directory = ['C:\GitHub\DouglasEtAl_UK_HEM_GMM\JD resampling\' ...
    'GAB - Rjb resampled data\'];

periods=[
    {'0010'},...
    {'0025'},...
    {'0050'},{'0075'},{'0100'},{'0150'},{'0200'},...
    {'0300'},{'0400'},{'0500'},{'0750'},{'1000'},{'1500'},{'2000'},...
    {'3000'},{'4000'},{'5000'},{'7500'},{'9999'}
    ];

for t=1:length(periods)
    for i=1:3 % Number of branches
        % Rjb original
        raeng_regressionhybriduk_resampled( ...
            periods(t), ...
            [directory,'original3bothrjb',char(periods(t)),'_gab.txt'], ...
            ['coeffukrjbboth_3branches_original_gab_',char(periods(t))], ...
            11, ...
            i);

        % Rjb reweighted
        % raeng_regressionhybriduk_resampled( ...
        %     periods(t), ...
        %     [directory,'reweighted3bothrjb',char(periods(t)),'_gab.txt'], ...
        %     ['coeffukrjbboth_3branches_reweighted_gab_',char(periods(t))], ...
        %     11, ...
        %     i);
        
        % Rrup original
        % raeng_regressionhybriduk_resampled( ...
        %     periods(t), ...
        %     [directory,'original3bothrrup',char(periods(t)),'_gab.txt'], ...
        %     ['coeffukrrupboth_3branches_original_gab_',char(periods(t))], ...
        %     11, ...
        %     i);

        % Rrup reweighted
        % raeng_regressionhybriduk_resampled( ...
        %     periods(t), ...
        %     [directory,'reweighted3bothrrup',char(periods(t)),'_gab.txt'], ...
        %     ['coeffukrrupboth_3branches_reweighted_gab_',char(periods(t))], ...
        %     11, ...
        %     i);
    end
end

%% JD files
% directory = ['C:\GitHub\DouglasEtAl_UK_HEM_GMM\JD resampling\' ...
%     'JD original - Rrup resampled\'];
% periods=[
%     {'0010'},...
%     {'0025'},...
%     % {'0050'},{'0075'},{'0100'},{'0150'},{'0200'},...
%     % {'0300'},{'0400'},{'0500'},{'0750'},{'1000'},{'1500'},{'2000'},...
%     % {'3000'},{'4000'},{'5000'},{'7500'},{'9999'}
%     ];
% 
% for t=1:length(periods)
%     for i=1:3 % Number of branches
%         % raeng_regressionhybriduk_resampled( ...
%         %     periods(t), ...
%         %     [directory,'originalweigths5bothrrup',char(periods(t)),'.txt'], ...
%         %     ['coeffrrupukboth_5branches_original_',char(periods(t))], ...
%         %     11, ...
%         %     i);
% 
%         raeng_regressionhybriduk_resampled( ...
%             periods(t), ...
%             [directory,'originalweights3bothrrup',char(periods(t)),'.txt'], ...
%             [directory,'coeffrrupukboth_3branches_original_gab_',char(periods(t))], ...
%             11, ...
%             i);
%     end
% end
